function [Age, BLine, TUG] = functionData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [AGE, BLINE, TUG] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [AGE, BLINE, TUG] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [Age, BLine, TUG] = importfile("C:\Users\Lenovo\Documents\UniversidadDistrital\semestre9\Ciber 3\Corte 3\Punto 2\Corte3Punto2MatLab\Datos.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Aug-2022 00:02:35

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Age", "BLine", "TUG"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Age", "BLine", "TUG"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Age = tbl.Age;
BLine = tbl.BLine;
TUG = tbl.TUG;
end